global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ueep-apps'
    static_configs:
      - targets:
        - 'app1:5000'
        - 'app2:5000'
        - 'app3:5000'
    metrics_path: '/metrics'
    scrape_interval: 10s
